<!-- ouc:editor wysiwyg="no" -->
<meta charset="utf-8"> 
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<link href="//netdna.bootstrapcdn.com/bootstrap/3.0.1/css/bootstrap.min.css" rel="stylesheet">
<style>
	ul#sidenav.nav { background-color: #E7E7E7; }
	ul#sidenav ul.nav li a { color: #FFFFFF; }
	ul#sidenav ul.nav li a:hover, ul#sidenav ul.nav li a:focus { color: #2A6496; }
	.footer {
		background-color: #111111;
		border-top-color: #000000;
		border-top-style: solid;
		border-top-width: 1px;
		color: #999999;
		margin-top:30px;
		padding-bottom: 15px;
		padding-left: 50px;
		padding-top: 15px;
	}
	.footer a { color: #FFFFFF; }
	.footer a:hover { -moz-text-blink: none;-moz-text-decoration-color: -moz-use-text-color;-moz-text-decoration-line: none;-moz-text-decoration-style: solid;color: #FFFFFF; }
</style>