<!-- ouc:editor wysiwyg="no" -->
<div class="row clearfix">
	<div class="col-sm-12">
		<h1>OmniUpdate Simple Site</h1>
	</div>
</div>	
<nav class="navbar navbar-default" role="navigation">
	<div class="navbar-header">
		<a class="navbar-brand" href="/">Home</a>
	</div>
	<div class="collapse navbar-collapse">
		<ul class="nav navbar-nav">
			<li><a href="/about/">About</a></li>
		</ul>
	</div>
</nav>